## COMMON ##
USE_CUDA: True
MODEL: Wavegram_Logmel_Cnn14
CKPT_PATH: "checkpoints/model.pth"
PRED_THRESH: 0.5

## TRAIN ##
# random seed
SEED:

# model
HALFTRAINED_PATH:
PRETRAINED_PATH: "audioset_tagging_cnn/Wavegram_Logmel_Cnn14_mAP=0.439.pth"
TRAIN_FROM: pre_conv0

# dataset
VALIDATION: False
SANITY_CHECK: True
LIKELIHOOD: [0, 1, 1]
AUDIO_DURATION: 5.0
NOISE: 0.00001

# optimization
NUM_WORKERS: 1
LOSS: BCELoss
BATCH_SIZE: 32
EPOCHS: 1000
OPTIMIZER: Adam
LR: 0.001

## TEST ##
WINDOW_SIZE: 5.0
STRIDE: 5.0
