## COMMON ##
USE_CUDA: True
MODEL: Wavegram_Logmel_Cnn14
CKPT_PATH: "checkpoints/model.pth"
PRED_THRESH: 0.5

## TRAIN ##
# random seed
SEED: 0

# model
HALFTRAINED_PATH:
PRETRAINED_PATH: "audioset_tagging_cnn/Wavegram_Logmel_Cnn14_mAP=0.439.pth"
TRAIN_FROM: conv_block1

# dataset
VALIDATION: False
SANITY_CHECK: True
LIKELIHOOD: [0, 1, 1]
AUDIO_DURATION: 5.0
NOISE: 0.00001

# optimization
NUM_WORKERS: 4
LOSS: BCELoss
BATCH_SIZE: 128
EPOCHS: 1000
OPTIMIZER: Adam
LR:
  LR: 0.001
  SCHEDULER: ExponentialLR
  KWARGS:
    gamma: 1.
RESUME: False

## TEST ##
WINDOW_SIZE: 5.0
STRIDE: 5.0
